#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# shellcheck disable=SC2016
/usr/local/bin/readsb \
  --net \
  --net-only \
  --quiet \
  --net-heartbeat 60 \
  --net-ro-size 1280 \
  --net-beast-reduce-interval "${REDUCE_INTERVAL}" \
  --net-connector "127.0.0.1,50005,beast_reduce_out" \
  --net-connector "${BEASTHOST}","${BEASTPORT}",beast_in \
  2>&1 | stdbuf -o0 sed --unbuffered '/^$/d' | stdbuf -o0 awk '{print "[planewatch-feed] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
  
  # stdbuf -o0 sed --unbuffered '/^$/d'  --  (remove blank lines from output)
  # awk -W interactive '{print "[planewatch-feed] " $0}'  --  (prefix log messages with "[planewatch-feed]")
