---

version: 2

updates:
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: "daily"
      time: "07:00"
      timezone: "Australia/Perth"
    assignees:
      - "mikenye"
    groups:
      docker-dependencies:
        applies-to: version-updates
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "daily"
      time: "07:00"
      timezone: "Australia/Perth"
    assignees:
      - "mikenye"
    groups:
      github-actions:
        applies-to: version-updates
        patterns:
          - "*"
