#!/usr/bin/with-contenv bash
#shellcheck shell=bash

# If mlat enabled, start mlat results tunnel
if [[ "${ENABLE_MLAT,,}" == "true" ]]; then
    # shellcheck disable=SC2016
    stunnel /etc/stunnel/stunnel_mlat_server.conf \
        2>&1 | stdbuf -o0 awk '{print "[mlat_tunnel_s] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
else
    sleep 86500
fi