#!/usr/bin/with-contenv bash
#shellcheck shell=bash

set -eo pipefail

# Set up variable to determine if acars_router should be started
START_ACARS_ROUTER="false"

# Set up array to hold command line args for acars_router
AR_CMD=()

# If user has specified an ACARS_HOST, attempt to pull ACARS and feed into stunnel
if [[ -n "${ACARS_HOST}" ]]; then
    AR_CMD+=("--send-tcp-acars" "127.0.0.1:55550")
    AR_CMD+=("--receive-tcp-acars" "${ACARS_HOST}:${ACARS_PORT:-5550}")
    START_ACARS_ROUTER="true"
fi

# If user has specified an VDLM2_HOST, attempt to pull ACARS and feed into stunnel
if [[ -n "${VDLM2_HOST}" ]]; then
    AR_CMD+=("--send-tcp-vdlm2" "127.0.0.1:55555")
    AR_CMD+=("--receive-tcp-vdlm2" "${VDLM2_HOST}:${VDLM2_PORT:-5550}")
    START_ACARS_ROUTER="true"
fi

# If debug logging requested, enable it
if [[ -n "$DEBUG_LOGGING" ]]; then
    : #pass
else
    AR_CMD+=("-v")
fi

# If ACARS or VDLM2 are enabled, then start the router
if [[ "${START_ACARS_ROUTER,,}" == "true" ]]; then

    python3 /opt/acars_router/acars_router.py "${AR_CMD[@]}" $AR_EXTRA_ARGS \
        2>&1 \
        | stdbuf -o0 awk '{print "[acars_router] " $0}'

else
    sleep 86500
fi
