#!/usr/bin/with-contenv bash
#shellcheck shell=bash

set -eo pipefail

if [[ -n "${ACARS_HOST}" ]]; then

    python3 /opt/acars_router/acars_router.py \
        --send-tcp-acars "127.0.0.1:55550" \
        --send-tcp-vdlm2 "127.0.0.1:55555" \
        2>&1 \
        | stdbuf -o0 sed --unbuffered '/^$/d' \
        | stdbuf -o0 awk '{print "[acars_router] " $0}'

else
    sleep 86500
fi