#!/usr/bin/with-contenv bash
#shellcheck shell=bash

# Start ACARS tunnel if required
if [[ -n "${ACARS_HOST}" ]]; then
    # shellcheck disable=SC2016
    stunnel /etc/stunnel/stunnel_acars.conf \
        2>&1 | stdbuf -o0 awk '{print "[acars_tunnel] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
else
    sleep 86500
fi