#!/usr/bin/with-contenv bash
#shellcheck shell=bash

if [[ -n "${BEASTHOST}" ]]; then
    # shellcheck disable=SC2016
    stunnel /etc/stunnel/stunnel_beast.conf \
        2>&1 | stdbuf -o0 awk '{print "[beast_tunnel] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
else
    sleep 86500
fi
