#!/usr/bin/with-contenv bash
# shellcheck shell=bash

NOCOLOR='\033[0m'
YELLOW='\033[1;33m'

# Set up timezone
if [ -z "${TZ}" ]; then
  echo -e "${YELLOW}WARNING: TZ environment variable not set${NOCOLOR}"
else
  ln -snf "/usr/share/zoneinfo/$TZ" /etc/localtime && echo "$TZ" > /etc/timezone
fi
