#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# Define bash colours
NOCOLOR='\033[0m'
LIGHTRED='\033[1;31m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'

# If troubleshooting:
if [[ -n "$DEBUG_LOGGING" ]]; then
    set -x
fi

# Check to make sure the correct command line arguments have been set
EXITCODE=0
if [ -z "${BEASTHOST}" ]; then
  echo -e "${LIGHTRED}ERROR: BEASTHOST environment variable not set${NOCOLOR}"
  EXITCODE=1
fi
if [ -z "${API_KEY}" ]; then
  echo -e "${LIGHTRED}ERROR: API_KEY environment variable was not set${NOCOLOR}"
  EXITCODE=1
fi

# If any errors above are fatal, don't proceed starting the container
if [ "$EXITCODE" -ne 0 ]; then
  exit 1
fi

exit "$EXITCODE"
