#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# ensure config directory exists
mkdir -p /etc/stunnel

# Configure stunnel for BEAST traffic
{
    if [[ -n "$DEBUG_LOGGING" ]]; then
        : #pass
    else
        echo "debug = 4"
    fi
    echo "foreground = yes"
    echo "syslog = no"
    echo ""
    echo "[planewatch-beast-tunnel]"
    echo "client = yes"
    echo "sni = ${API_KEY}"
    echo "accept =  127.0.0.1:50005"
    echo "connect = ${PW_FEED_DESTINATION_HOSTNAME}:${PW_FEED_DESTINATION_BEAST_PORT}"
    echo "CApath = /etc/ssl/certs"
    echo "verifyChain = yes"
    echo "checkHost = ${PW_FEED_DESTINATION_HOSTNAME}"
    echo "TIMEOUTconnect = 10"
    echo ""
} > /etc/stunnel/stunnel_beast.conf

# Configure stunnel for ACARS traffic
{
    if [[ -n "$DEBUG_LOGGING" ]]; then
        : #pass
    else
        echo "debug = 4"
    fi
    echo "foreground = yes"
    echo "syslog = no"
    echo ""
    echo "[planewatch-acars-tunnel]"
    echo "client = yes"
    echo "sni = ${API_KEY}"
    echo "accept =  127.0.0.1:55550"
    echo "connect = ${PW_FEED_DESTINATION_HOSTNAME}:${PW_FEED_DESTINATION_ACARS_PORT}"
    echo "CApath = /etc/ssl/certs"
    echo "verifyChain = yes"
    echo "checkHost = ${PW_FEED_DESTINATION_HOSTNAME}"
    echo "TIMEOUTconnect = 10"
    echo ""
} > /etc/stunnel/stunnel_acars.conf

# Configure stunnel for VDLM2 traffic
{
    if [[ -n "$DEBUG_LOGGING" ]]; then
        : #pass
    else
        echo "debug = 4"
    fi
    echo "foreground = yes"
    echo "syslog = no"
    echo ""
    echo "[planewatch-vdlm2-tunnel]"
    echo "client = yes"
    echo "sni = ${API_KEY}"
    echo "accept =  127.0.0.1:55555"
    echo "connect = ${PW_FEED_DESTINATION_HOSTNAME}:${PW_FEED_DESTINATION_VDLM2_PORT}"
    echo "CApath = /etc/ssl/certs"
    echo "verifyChain = yes"
    echo "checkHost = ${PW_FEED_DESTINATION_HOSTNAME}"
    echo "TIMEOUTconnect = 10"
    echo ""
} > /etc/stunnel/stunnel_vdlm2.conf
