---
name: Linting (Hadolint)

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - 'Dockerfile'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  hadolint:
    name: Run hadolint against docker files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Pull hadolint/hadolint:latest Image
        run: docker pull hadolint/hadolint:latest
      - name: Run hadolint against Dockerfiles
        shell: bash
        run: |
          set -euo pipefail
          mapfile -d '' -t DOCKERFILES < <(find . -type f -iname 'Dockerfile*' -print0)
          docker run --rm -i \
            --volume "${PWD}:/workdir" \
            --workdir /workdir \
            --entrypoint hadolint \
            hadolint/hadolint \
            --ignore DL3003 \
            --ignore DL3006 \
            --ignore DL3010 \
            --ignore DL4001 \
            --ignore DL3007 \
            --ignore DL3008 \
            --ignore SC2068 \
            --ignore SC1091 \
            --ignore DL3013 \
            "${DOCKERFILES[@]}"
